/**
 * @gitgecko/review/security-hook — per-dialect mutates-deny formatting (Phase 4.4 / T5).
 *
 * THE WEDGE (W5, P-plugin-7): the `mutatesDenyList` derived by the Registry
 * must be formatted per active runtime adapter's dialect. Each native agent
 * expresses denies differently:
 *  - Claude Code: `permissions.deny` gitignore globs in managed-settings + `--disallowedTools` flag
 *  - OpenCode: wildcard patterns under per-tool `read`/`edit` permission keys
 *  - Codex: `--disallowedTools` flag + read-only sandbox flag
 *
 * Salvage source (verbatim patterns):
 *  - `.refs/01-pr-review/pullfrog-main/agents/nativeFsDenies.ts` — the per-dialect
 *    deny surfaces (GIT_NATIVE_WRITE_DENY_CLAUDE / OPENCODE)
 *  - `.refs/01-pr-review/pullfrog-main/agents/claudePretoolGate.ts` — the PreToolUse
 *    hook script that hard-blocks mutating tools from subagents
 *
 * Battle-lesson (pullfrog claude.ts:96-108): `--disallowedTools` alone leaked
 * under `--dangerously-skip-permissions`; the managed-settings `permissions.deny`
 * is the authoritative bypass-immune layer. gitgecko wires deny into BOTH.
 */

// --- The canonical deny surfaces (worktree-relative) ------------------------
// Salvage provenance (G11): these globs are verbatim from
// `.refs/01-pr-review/pullfrog-main/agents/nativeFsDenies.ts` (P-plugin-7).
// These are the ALWAYS-DENIED surfaces for a read-only review (W5). The .git
// write-deny is free (nothing legitimately writes .git via native tools during
// review) and blocks the git-hooks/git-filter exec vector. The .git/config
// read-deny is narrow (credential/token leak surface).

/** Tools denied via the Claude `permissions.deny` managed-settings layer. */
export const GIT_WRITE_DENY_CLAUDE: readonly string[] = [
  "Edit(.git)",
  "Edit(.git/**)",
  "Edit(**/.git)",
  "Edit(**/.git/**)",
];

/** Tools denied read via the Claude `permissions.deny` layer. */
export const GIT_READ_DENY_CLAUDE: readonly string[] = ["Read", "Grep", "Glob"].map(
  (tool) => `${tool}(.git/config)`,
);

/** OpenCode wildcard deny patterns for write (spread into `edit` ruleset). */
export const GIT_WRITE_DENY_OPENCODE: Readonly<Record<string, "deny">> = {
  ".git": "deny",
  ".git/*": "deny",
  "*/.git": "deny",
  "*/.git/*": "deny",
};

/** OpenCode wildcard deny pattern for read (spread into `read` ruleset). */
export const GIT_READ_DENY_OPENCODE: Readonly<Record<string, "deny">> = {
  ".git/config": "deny",
};

// --- Per-dialect formatters --------------------------------------------------

export type AgentDialect = "claude-code" | "codex" | "opencode" | "generic";

/**
 * Format the deny list for the active agent's CLI flag dialect.
 * Used by the agent plugs to construct the `--disallowedTools` flag.
 */
export const formatDisallowedTools = (
  dialect: AgentDialect,
  mutatesDenyList: readonly string[],
): string => {
  // All dialects use the comma-separated `--disallowedTools` flag shape.
  // Claude also needs the managed-settings deny (formatManagedSettingsDeny).
  return [...mutatesDenyList].join(",");
};

/**
 * Format the managed-settings `permissions.deny` for Claude Code. This is the
 * bypass-immune authoritative layer (survives `--dangerously-skip-permissions`).
 * Salvaged from pullfrog claudePretoolGate.ts:124-157.
 */
export const formatClaudeManagedSettingsDeny = (
  mutatesDenyList: readonly string[],
): { permissions: { deny: readonly string[] } } => {
  return {
    permissions: {
      deny: [
        ...mutatesDenyList.map((tool) => `${tool}(**)`),
        ...GIT_WRITE_DENY_CLAUDE,
        ...GIT_READ_DENY_CLAUDE,
      ],
    },
  };
};

/**
 * Build the Claude PreToolUse hook script source. This script is written to a
 * tmpdir and registered via `--settings <path>`. It reads JSON stdin, checks
 * `agent_id` (subagent discriminator) + `tool_name` against the deny set,
 * exits 0 (allow) or 2 (block + stderr to model).
 *
 * Salvaged verbatim from pullfrog claudePretoolGate.ts:48-98.
 */
export const buildClaudePretoolGateSource = (
  deniedTools: readonly string[],
  mcpPrefix = "mcp__pullfrog__",
): string => {
  return `#!/usr/bin/env node
// AUTOGENERATED by gitgecko. PreToolUse hook that hard-blocks state-mutating
// MCP tool calls from subagents. Salvaged from pullfrog claudePretoolGate.ts.

const SUBAGENT_DENIED_TOOLS = new Set(${JSON.stringify(deniedTools)});

function stripMcpPrefix(toolName) {
  if (toolName.startsWith("${mcpPrefix}")) return toolName.slice("${mcpPrefix}".length);
  return toolName;
}

let stdin = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => { stdin += chunk; });
process.stdin.on("end", () => {
  let payload;
  try { payload = JSON.parse(stdin); } catch {
    process.stderr.write("gitgecko-pretool-gate: malformed stdin JSON\\n");
    process.exit(1);
  }
  const toolName = typeof payload?.tool_name === "string" ? payload.tool_name : "";
  const agentId = typeof payload?.agent_id === "string" ? payload.agent_id : "";
  if (!agentId) process.exit(0); // main thread — allow
  const bare = stripMcpPrefix(toolName);
  if (!SUBAGENT_DENIED_TOOLS.has(bare)) process.exit(0); // not denied — allow
  process.stderr.write(
    "subagent attempted denied tool '" + bare + "'. State-changing tools are " +
    "reserved for the orchestrator. Report findings back.\\n"
  );
  process.exit(2); // block (exit 2 = deny + stderr to model)
});
`;
};

/**
 * Build the `--settings` JSON for Claude Code with the PreToolUse hook + deny.
 * Salvaged from pullfrog claudePretoolGate.ts:124-157.
 */
export const buildClaudeSettings = (
  deniedTools: readonly string[],
  gateScriptPath: string,
): Record<string, unknown> => {
  return {
    permissions: {
      deny: [
        ...deniedTools.map((t: string) => `${t}(**)`),
        ...GIT_WRITE_DENY_CLAUDE,
        ...GIT_READ_DENY_CLAUDE,
      ],
    },
    hooks: {
      PreToolUse: [
        {
          matcher: "^mcp__",
          hooks: [{ type: "command", command: `node ${gateScriptPath}` }],
        },
      ],
    },
  };
};
